<a href="https://colab.research.google.com/github/ANUKOOL324/Data_Analytics/blob/main/3_Pandas%20Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_25_Pandas Cleaning.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [57]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.18.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [58]:
import pandas as pd
from datasets import load_dataset

In [59]:
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

## 🟩 Sort by Salary (1.25.1)

In [60]:
df.sort_values(by='salary_year_avg' , inplace=True, ignore_index=True)

---

In [61]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Data Engineer,Data Engineer - Hadoop,Brazil,via LinkedIn,Full-time,False,Brazil,2023-12-09 10:05:30,True,False,Brazil,year,15000.0,NaN,Net2Source Inc.,"['java', 'python', 'oracle', 'aws', 'hadoop', ...","{'cloud': ['oracle', 'aws'], 'libraries': ['ha..."
1,Business Analyst,Operations Analyst,Anywhere,via Wellfound,Full-time,True,Bangladesh,2023-05-16 18:39:05,False,False,Bangladesh,year,16500.0,NaN,Forward,None,None
2,Data Engineer,Showwcase Elite - Data Engineer,Anywhere,via Wellfound,Full-time,True,Australia,2023-07-07 08:20:46,False,False,Australia,year,20000.0,NaN,Showwcase,"['go', 'sql', 'python', 'react', 'flutter', 'a...","{'libraries': ['react', 'flutter', 'airflow'],..."
3,Data Engineer,Lead Data Engineer,"Kansas City, MO",via Adzuna,Full-time,False,"Florida, United States",2023-02-11 19:12:33,False,False,United States,year,23496.0,NaN,American Century Investments,"['python', 'java', 'r', 'sas', 'sas', 'mysql',...","{'analyst_tools': ['sas', 'ssis', 'tableau'], ..."
4,Data Engineer,Data Engineer Jobs In Flipdish for Engineering...,"Karachi, Pakistan",via Get Daily Fresh Jobs Opportunity,Full-time,False,Pakistan,2023-09-23 22:28:39,False,False,Pakistan,year,24000.0,NaN,Flipdish,"['python', 'java', 'scala', 'sql', 'nosql', 'h...","{'analyst_tools': ['excel'], 'libraries': ['ha..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [62]:
df['salary_year_avg']

0         15000.0
1         16500.0
2         20000.0
3         23496.0
4         24000.0
           ...
785736        NaN
785737        NaN
785738        NaN
785739        NaN
785740        NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [63]:
df[df['salary_year_avg'].notna()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Data Engineer,Data Engineer - Hadoop,Brazil,via LinkedIn,Full-time,False,Brazil,2023-12-09 10:05:30,True,False,Brazil,year,15000.0,NaN,Net2Source Inc.,"['java', 'python', 'oracle', 'aws', 'hadoop', ...","{'cloud': ['oracle', 'aws'], 'libraries': ['ha..."
1,Business Analyst,Operations Analyst,Anywhere,via Wellfound,Full-time,True,Bangladesh,2023-05-16 18:39:05,False,False,Bangladesh,year,16500.0,NaN,Forward,None,None
2,Data Engineer,Showwcase Elite - Data Engineer,Anywhere,via Wellfound,Full-time,True,Australia,2023-07-07 08:20:46,False,False,Australia,year,20000.0,NaN,Showwcase,"['go', 'sql', 'python', 'react', 'flutter', 'a...","{'libraries': ['react', 'flutter', 'airflow'],..."
3,Data Engineer,Lead Data Engineer,"Kansas City, MO",via Adzuna,Full-time,False,"Florida, United States",2023-02-11 19:12:33,False,False,United States,year,23496.0,NaN,American Century Investments,"['python', 'java', 'r', 'sas', 'sas', 'mysql',...","{'analyst_tools': ['sas', 'ssis', 'tableau'], ..."
4,Data Engineer,Data Engineer Jobs In Flipdish for Engineering...,"Karachi, Pakistan",via Get Daily Fresh Jobs Opportunity,Full-time,False,Pakistan,2023-09-23 22:28:39,False,False,Pakistan,year,24000.0,NaN,Flipdish,"['python', 'java', 'scala', 'sql', 'nosql', 'h...","{'analyst_tools': ['excel'], 'libraries': ['ha..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21998,Data Scientist,Staff Data Scientist/Quant Researcher,Anywhere,via LinkedIn,Full-time,True,Sudan,2023-08-16 16:11:58,False,False,Sudan,year,550000.0,NaN,Selby Jennings,"['python', 'sql']","{'programming': ['python', 'sql']}"
21999,Data Scientist,Geographic Information Systems Analyst - GIS A...,"New York, NY",via ZipRecruiter,Full-time,False,"New York, United States",2023-12-27 18:00:12,False,False,United States,year,585000.0,NaN,ReServe,['excel'],{'analyst_tools': ['excel']}
22000,Data Analyst,Data Analyst,Anywhere,via Y Combinator,Full-time,True,India,2023-02-20 15:13:44,True,False,India,year,650000.0,NaN,Mantys,None,None
22001,Senior Data Scientist,Senior Data Scientist,"Pretoria, South Africa",via Adzuna,Full-time,False,South Africa,2023-11-02 10:31:43,False,False,South Africa,year,890000.0,NaN,MSP Staffing LTD,"['python', 'sql', 'java', 'c#', 'databricks', ...","{'cloud': ['databricks', 'azure'], 'libraries'..."
22002,Data Scientist,Data Scientist,"Madison, SD",via Cooperative Career Center,Full-time,False,"Illinois, United States",2023-05-04 19:06:06,False,True,United States,year,960000.0,NaN,"East River Electric Power Cooperative, Inc.","['java', 'c++', 'python', 'r']","{'programming': ['java', 'c++', 'python', 'r']}"

## 🟩 Create Remote Column (1.25.2)

In [64]:
#solution
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Data Engineer,Data Engineer - Hadoop,Brazil,via LinkedIn,Full-time,False,Brazil,2023-12-09 10:05:30,True,False,Brazil,year,15000.0,NaN,Net2Source Inc.,"['java', 'python', 'oracle', 'aws', 'hadoop', ...","{'cloud': ['oracle', 'aws'], 'libraries': ['ha..."
1,Business Analyst,Operations Analyst,Anywhere,via Wellfound,Full-time,True,Bangladesh,2023-05-16 18:39:05,False,False,Bangladesh,year,16500.0,NaN,Forward,None,None
2,Data Engineer,Showwcase Elite - Data Engineer,Anywhere,via Wellfound,Full-time,True,Australia,2023-07-07 08:20:46,False,False,Australia,year,20000.0,NaN,Showwcase,"['go', 'sql', 'python', 'react', 'flutter', 'a...","{'libraries': ['react', 'flutter', 'airflow'],..."
3,Data Engineer,Lead Data Engineer,"Kansas City, MO",via Adzuna,Full-time,False,"Florida, United States",2023-02-11 19:12:33,False,False,United States,year,23496.0,NaN,American Century Investments,"['python', 'java', 'r', 'sas', 'sas', 'mysql',...","{'analyst_tools': ['sas', 'ssis', 'tableau'], ..."
4,Data Engineer,Data Engineer Jobs In Flipdish for Engineering...,"Karachi, Pakistan",via Get Daily Fresh Jobs Opportunity,Full-time,False,Pakistan,2023-09-23 22:28:39,False,False,Pakistan,year,24000.0,NaN,Flipdish,"['python', 'java', 'scala', 'sql', 'nosql', 'h...","{'analyst_tools': ['excel'], 'libraries': ['ha..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [65]:
df['remote']=df['job_work_from_home']

In [66]:
df['remote']

0         False
1          True
2          True
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: remote, Length: 785741, dtype: bool

---

## 🟩 Extract Year from Date (1.25.3)

In [67]:
#solution
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  remote                 785741 non-null  bool
dtypes: bool(4), float64(2), object(12)
memory usage: 86.9+ MB

In [68]:
df['job_posted_date'] # it is object(string type) so make it datatime data type

0         2023-12-09 10:05:30
1         2023-05-16 18:39:05
2         2023-07-07 08:20:46
3         2023-02-11 19:12:33
4         2023-09-23 22:28:39
                 ...
785736    2023-03-13 06:16:16
785737    2023-03-12 06:18:18
785738    2023-03-12 06:32:36
785739    2023-03-12 06:32:15
785740    2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: object

In [69]:
df['job_posted_date']=pd.to_datetime(df.job_posted_date)
df.job_posted_date.dt.year

0         2023
1         2023
2         2023
3         2023
4         2023
          ...
785736    2023
785737    2023
785738    2023
785739    2023
785740    2023
Name: job_posted_date, Length: 785741, dtype: int32

In [70]:
df.job_posted_date.dt.month

0         12
1          5
2          7
3          2
4          9
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

---

## 🟨 Drop Missing Salaries (1.25.4)

In [71]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,remote
0,Data Engineer,Data Engineer - Hadoop,Brazil,via LinkedIn,Full-time,False,Brazil,2023-12-09 10:05:30,True,False,Brazil,year,15000.0,NaN,Net2Source Inc.,"['java', 'python', 'oracle', 'aws', 'hadoop', ...","{'cloud': ['oracle', 'aws'], 'libraries': ['ha...",False
1,Business Analyst,Operations Analyst,Anywhere,via Wellfound,Full-time,True,Bangladesh,2023-05-16 18:39:05,False,False,Bangladesh,year,16500.0,NaN,Forward,None,None,True
2,Data Engineer,Showwcase Elite - Data Engineer,Anywhere,via Wellfound,Full-time,True,Australia,2023-07-07 08:20:46,False,False,Australia,year,20000.0,NaN,Showwcase,"['go', 'sql', 'python', 'react', 'flutter', 'a...","{'libraries': ['react', 'flutter', 'airflow'],...",True
3,Data Engineer,Lead Data Engineer,"Kansas City, MO",via Adzuna,Full-time,False,"Florida, United States",2023-02-11 19:12:33,False,False,United States,year,23496.0,NaN,American Century Investments,"['python', 'java', 'r', 'sas', 'sas', 'mysql',...","{'analyst_tools': ['sas', 'ssis', 'tableau'], ...",False
4,Data Engineer,Data Engineer Jobs In Flipdish for Engineering...,"Karachi, Pakistan",via Get Daily Fresh Jobs Opportunity,Full-time,False,Pakistan,2023-09-23 22:28:39,False,False,Pakistan,year,24000.0,NaN,Flipdish,"['python', 'java', 'scala', 'sql', 'nosql', 'h...","{'analyst_tools': ['excel'], 'libraries': ['ha...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete...",False
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi...",False
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",False
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",False
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}",False

In [72]:
df=df.dropna(subset=['salary_year_avg'])

In [73]:
df['salary_year_avg']

0         15000.0
1         16500.0
2         20000.0
3         23496.0
4         24000.0
           ...
21998    550000.0
21999    585000.0
22000    650000.0
22001    890000.0
22002    960000.0
Name: salary_year_avg, Length: 22003, dtype: float64

---